---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: example
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        app: firewall
      route:
        - destination:
          destinationSelector:
            app: iperf-server
    - match:
      sourceSelector:
        app: router1
      route:
        - destination:
          destinationSelector:
            app: firewall
    #- match:
    #  sourceSelector:
    #    link: r1-r2 
    #  route:
    #    - destination:
    #      destinationSelector:
    #        app: router2
    - match:
      route:
        - destination:
          destinationSelector:
            app: router1
