---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: rfchain
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        link: sgi
      route:
        - destination:
          destinationSelector:
            app: iperf-server
    - match:
      sourceSelector:
        link: r1f
      route:
        - destination:
          destinationSelector:
            app: firewall
    - match:
      sourceSelector:
        link: c1r
      route:
        - destination:
          destinationSelector:
            app: router1
