---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "router4"
      networkservicemesh.io/impl: "rfchain"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "router4"
        networkservicemesh.io/impl: "rfchain"
    spec:
      containers:
        - name: sidecar-nsc
          image: networkservicemesh/topology-sidecar-nsc:master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              networkservicemesh.io/socket: "1"
          env:
            - name: NS_NETWORKSERVICEMESH_IO
              value: "rfchain/rfeth41?link=r4-r1&peerif=rfeth14,rfchain/rfeth45?link=r4-r5&peerif=rfeth54"
        - name: sidecar-nse
          image: networkservicemesh/topology-sidecar-nse:master
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "rfchain"
            - name: ENDPOINT_LABELS
              value: "app=router4"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.4.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: router
          image: networkservicemesh/topology-qrtr:master
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: startup-config
              mountPath: /etc/quagga/zebra.conf
              subPath: zebra.conf
      volumes:
        - name: startup-config
          configMap:
            name: qrtr-4
metadata:
  name: router4
  annotations:
    ns.networkservicemesh.io: rfchain/r4f?link=r4f
  namespace: default
---
apiVersion: v1
metadata:
  name: qrtr-4
data:
  zebra.conf: |
    !
    hostname qrtr-4
    !
    interface lo
      ip address 192.0.2.4/32
      exit
    !
kind: ConfigMap
